title: ERICSJ1998 GIT BLOG
description: > # this means to ignore newlines until "baseurl:"
  한국에 사는 평범한 그림그리기 좋아하는 컴공쟁이의 깃헙페이지
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ericsj1998.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: ericsj1998 # add your name
author-img: ericsj1998pro.jpg # add your photo
about-author: |
  깃헙 사이트 프로토타입, 전공 내용과 드로잉 및 커미션 위주로 올리는 깃헙 블로그;
  서포터즈 활동과 겸해 차츰 업데이트 해나갈 예정; 
  현재 카테고리 작업중;  
  프로필 밑 favicon 그리는중;
  최종목표는 나의 그림으로 가득 찬 코딩블로그;
social-twitter: sdf # add your Twitter handle
social-facebook: sdf # add your Facebook handle
social-github: ericsj1998 # add your Github handle
social-linkedin: sdfsf # add your Linkedin handle
social-email: ericsj1998@naver.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
remote_theme: artemsheludko/flexible-jekyll


